Resources:
  MyInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0e731c8a588258d0d
      Tags: 
        - Key: "Name"
          Value: "change1"

