Resources:
  MyInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e731c8a588258d0d
      Tags: 
        - Key: "Name"
          Value: !Join 
            - " "
            - - "My Instance in"
              - !Ref AWS::Region